export const mockData = {
  apps: [
    { app_id: "interviewer", status: "active", has_plugin: true },
    { app_id: "support_agent", status: "active", has_plugin: true },
  ],
  knowledgeBases: [
    {
      id: "interviewer:jd_kb",
      app_id: "interviewer",
      kb_key: "jd_kb",
      text_field: "content",
      name: "面试 JD 库",
      type: "static_kb",
      collection: "kb_interviewer_jd",
      docs: 1280,
      chunks: 7421,
      owner: "interviewer",
      access: "public",
      updated_at: "2 小时前",
      log: [
        "02:12 UTC - 更新 24 条文档",
        "01:54 UTC - 删除 3 条文档",
        "01:30 UTC - 规范化 128 条",
      ],
      histogram: [72, 58, 90, 64],
    },
    {
      id: "interviewer:user_profile_kb",
      app_id: "interviewer",
      kb_key: "user_profile_kb",
      text_field: "text",
      name: "用户画像",
      type: "user_upload",
      collection: "kb_user_profile",
      docs: 320,
      chunks: 2440,
      owner: "shared",
      access: "restricted",
      updated_at: "10 分钟前",
      log: [
        "02:10 UTC - 摄取 12 份简历",
        "01:40 UTC - 刷新 5 条画像",
        "00:58 UTC - 标记 3 条记录",
      ],
      histogram: [30, 52, 44, 70],
    },
  ],
  stores: [
    {
      name: "SQLite",
      status: "online",
      description: "会话身份与记忆元数据",
      latency: "2ms",
    },
    {
      name: "Weaviate",
      status: "online",
      description: "向量集合与语义检索",
      latency: "34ms",
    },
    {
      name: "MinIO",
      status: "online",
      description: "原始文档与会话历史",
      latency: "18ms",
    },
  ],
  ingestion: [
    {
      title: "面试 JD 库已刷新",
      time: "2 小时前",
      meta: "更新 24 条，删除 3 条",
    },
    {
      title: "用户画像摄取",
      time: "10 分钟前",
      meta: "新增 12 份简历，规范化 4 条",
    },
  ],
  vectors: 10432,
};
